CREATE TABLE IF NOT EXISTS tb_pedidos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      id_cliente BIGINT NOT NULL,
      data_pedido TIMESTAMP NOT NULL DEFAULT NOW(),
      chave_pagamento VARCHAR(255),
      observacoes VARCHAR(255),
      status VARCHAR(20) NOT NULL DEFAULT 'REALIZADO' CHECK (
            status IN ('REALIZADO', 'PAGO', 'FATURADO', 'ENVIADO', 'ERRO_PAGAMENTO', 'PREPARANDO_ENVIO')
      ),
      total DECIMAL(16,2) NOT NULL,
      codigo_rastreio VARCHAR(255),
      url_nf VARCHAR(255)
);