spring:
  application:
    name: clientes

  datasource:
    url: jdbc:postgresql://localhost:5432/icomprasclientes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver