services:
  postgres:
    image: postgres:15-alpine
    container_name: db_icompras
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: icompraspedidos
      POSTGRES_MULTIPLE_DATABASES: icomprasprodutos,icomprasclientes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  postgres_data: